name: Run E2E tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 20

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-brown.vercel.app/"
        with:
          working-directory: ./
          build: npm run build
          start: npm start
